[build]
builder = "dockerfile"

[services.backend-web]
dockerfilePath = "backend-web/Dockerfile"
buildContext = "backend-web"

[services.backend-android]
dockerfilePath = "backend-android/Dockerfile"
buildContext = "backend-android"

[services.frontend]
dockerfilePath = "frontend/Dockerfile"
buildContext = "frontend"
